name: counter_with_theme
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^10.1.0
  go_router: ^11.1.2
  intl: ^0.18.1
  logger: ^2.0.2+1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.1
  weather: ^3.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib/core/services/localization_service/l10n
  output_dir: lib/core/services/localization_service/generated
